### ISSUE TITLE
After login, subsequent calls causes 401 - Unauthorized

### ISSUE THREAD

**Issue by amgart** [TheMich4/iracing-api#6]
Hi!

I have an Electron app using the iracing-api library with 0.1.11 (0.1.12 login is not working).
After the /auth call is successful I try to execute a call (getCars, getTracks, ... ) and they return 401 - Unauthorized.

Some more details:

My httpClient method looks like this: 

`async login(loginDTO: LoginDTO): Promise<LoginResponseDTO> {`
    `const iRClient = new IracingAPI();`
    `await iRClient.login(loginDTO.email, loginDTO.password);`
    `await iRClient.getSeriesSeasons();`
   `... more stuff in here`
  `}`

If you need any more info please let me know. Thanks!

Albert

**Comment by TheMich4** [comment]
As @zzm634 mentioned, those issues are related to bug in login method that was fixed.
Additionally you are right, I was already thinking about adding additional validation for login success and auto re-login when session expires. This should be added soon.

**Comment by amgart** [comment]
Hi again!

I don't know if I fully understand what you mean. I tried the following code:

return iRClient.login(loginDTO.email, loginDTO.password).then(res => {
      if (res?.data) {
        console.log('-- hey!!');
        this.iRClient.getSeriesSeasons();
        return res.data;
      }
    });
    
But the output is the same. Here is the response of the auth call from the Development Tools:

![image](https://github.com/TheMich4/iracing-api/assets/50016171/4eb5a418-1d0c-46d2-84f8-6b66bda0ffee)

And here is the next call from the 'getSeriesSeasons()':

![image](https://github.com/TheMich4/iracing-api/assets/50016171/334c759c-e77b-41fc-ae1f-7bbf141ba423)

This are the headers of the request of the 'season's call (in case if helps):

![image](https://github.com/TheMich4/iracing-api/assets/50016171/19ace288-40fb-4e91-bcba-71376531e364)

And the cookies:

![image](https://github.com/TheMich4/iracing-api/assets/50016171/bdef9c34-07fc-455b-9b8d-f0b233084d67)

I don't know if I am wrong but if I try directly from the browser, the 'seasons' call has the authtoken_members cookie, but here is not present. Is that what ou meant? Am I doing something wrong possibly?

Thanks for your help! :)

Albert

**Comment by amgart** [comment]
@TheMich4 , you are right, probably I messed it up while applying changes trying to make it work. Fixed the code but still not working. The second call is still returning 401.

I am actually showing the current code screenshot:

![image](https://github.com/TheMich4/iracing-api/assets/50016171/9bfe18ca-0c7d-46f1-98a9-d9e7e41bae21)

Seems quite strange. It should be a simple code and I am not able to make it work :(

**Comment by amgart** [comment]
Hi again,
I have created a 'Hello world' ng project and added the library with the 'login' and the 'getSeriesSeason' calls as mentioned above, run 'npm install' and then execute 'ng serve'.
The result is this error:

![image](https://github.com/TheMich4/iracing-api/assets/50016171/2c566cd4-412f-4e24-a195-8ed5502b90e3)

After fixing it with the first option (npm i --save-dev ...), the error is gone but the calls produces the 401 again.
To be honest I am not an expert on typescript, node, and Angular but I am thinking that maybe the 'cookie' management is doing something strange in a web application project (as the code you mentioned before does not seem like a web application project. I didn't have the opportunity to check it out and test it yet, sorry).
Could the previous error be related?

You can find the code in this repo in case you have the opportunity to check it out: https://github.com/amgart/iracing-api-test

I really appreciate your help! Thank you so much!

Albert

**Comment by amgart** [comment]
Hi again! 
Sorry for the delay, I have been busy these days. I have some new updates.

I tried my project with the newest version (0.2.2) but the issue still remains (401 in subsequent calls). However, I tried adding your project 'iracing-api-class-test' as a subproject in my repo and it is working.
So... same environment but running the subproject with node command, works. But running it from an Angular component in a web application is not working (both codes are the same but running from different places).
To be honest... I do not have more details on why is not working.

I will try to make a workaround to run the code as you are doing and use the info in my web app somehow but.. it would be great to have the library running without any workaround.
Thanks for your help!! :)

**Comment by zzm634** [comment]
Not sure if it's related to your issue, but I noticed that I'd start to get 401 responses about an hour after logging in. I guess the auth token needs to be refreshed.  I got around it by just creating a new client and logging in again whenever this happens.
